### ISSUE TITLE
eslint @typescript-eslint/unbound-method flagging

### ISSUE THREAD

**Issue by bobbypiper** [lifespikes/laravel-precognition-react#1]
Nice job on this package, I'm using this in one of my projects.

The only issue I've stumbled on is tyescript eslint complaining about `@typescript-eslint/unbound-method` returning of `$this` in the `validate` and `validateAndSetDataByKeyValuePair` methods.

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/unbound-method.md

I'm happy to submit a PR to resolve if you'd like.

**Comment by felipeva** [comment]
Hi @bobbypiper, thank you!

Glad you found this package. Sure, if you'd like to submit a PR, that'd be awesome. I'll review it asap.
